# Generated by Django 2.0.3 on 2019-10-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.IntegerField()),
                ('tmdb_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('rating_avg', models.FloatField(default=0)),
                ('rating_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('timestamp', models.IntegerField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies')),
            ],
        ),
        migrations.AddField(
            model_name='links',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
        ),
    ]
