# Generated by Django 2.0.3 on 2019-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='rating_avg',
        ),
    ]
