# Generated by Django 2.0.3 on 2019-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191029_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='ratingamount',
            new_name='rating_amount',
        ),
    ]
