# Generated by Django 2.0.3 on 2019-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191029_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
