# Generated by Django 2.0.3 on 2019-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating_avg',
            field=models.FloatField(default=0, null=True),
        ),
    ]
