# Generated by Django 2.0.3 on 2019-10-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191029_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='rating_amount',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='rating_avg',
        ),
    ]
